// generated from rosidl_typesupport_introspection_c/resource/idl__rosidl_typesupport_introspection_c.h.em
// with input from cuadriga_ctl_platform_interfaces:msg/CmdThrottleMsg.idl
// generated code does not contain a copyright notice

#ifndef CUADRIGA_CTL_PLATFORM_INTERFACES__MSG__DETAIL__CMD_THROTTLE_MSG__ROSIDL_TYPESUPPORT_INTROSPECTION_C_H_
#define CUADRIGA_CTL_PLATFORM_INTERFACES__MSG__DETAIL__CMD_THROTTLE_MSG__ROSIDL_TYPESUPPORT_INTROSPECTION_C_H_

#ifdef __cplusplus
extern "C"
{
#endif


#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_typesupport_interface/macros.h"
#include "cuadriga_ctl_platform_interfaces/msg/rosidl_typesupport_introspection_c__visibility_control.h"

ROSIDL_TYPESUPPORT_INTROSPECTION_C_PUBLIC_cuadriga_ctl_platform_interfaces
const rosidl_message_type_support_t *
ROSIDL_TYPESUPPORT_INTERFACE__MESSAGE_SYMBOL_NAME(rosidl_typesupport_introspection_c, cuadriga_ctl_platform_interfaces, msg, CmdThrottleMsg)();

#ifdef __cplusplus
}
#endif

#endif  // CUADRIGA_CTL_PLATFORM_INTERFACES__MSG__DETAIL__CMD_THROTTLE_MSG__ROSIDL_TYPESUPPORT_INTROSPECTION_C_H_
