circuit1:     
  ros__parameters:


    goal_points: [8.270,-4.142,0.0,
                  11.718,-8.107,0.0,
                  17.190,-11.194,0.0,
                  22.229,-15.827,0.0,
                  26.572,-19.375,0.0,
                  31.240,-23.349,0.0,
                  32.861,-26.692,0.0]  # Coordenadas de la meta en Unity

    republish_hz: 2.0      # frecuencia a la que re‑publica la meta activa

    # Importante para que el circuito termine y el supervisor pueda cambiar
    loop: false
    signal_done_on_last: true
    hold_when_done: true
    
    